### ISSUE TITLE
fix latest version button

### ISSUE THREAD

**Issue by schveiguy** [vibe-d/vibed.org#57]
Current website shows latest version to be 0.7.23. The link isn't even valid.

I'm not sure how this is supposed to work. According to the code, it periodically scans the "public/files" directory for new versions of vibe.d. Not sure if they ever appear there, it seems like the version that is displayed is the version in the code (see [here](https://github.com/vibe-d/vibed.org/blob/9901664171f4ac5e3afcc19293ab6785d3b16c28/source/app.d#L12)).

If there is an issue with the web site where it's not getting the version info from code.dlang.org, that button should just link to the base page (i.e. http://code.dlang.org/packages/vibe-d) and say something generic like "Latest" instead of the actual version number.

I'm not knowledgeable about the web site enough to know if there is something else that is supposed to fetch these versions which is broken. I'll also note that the downloads link seems to be broken.

**Comment by schveiguy** [comment]
Seems to be better, not sure what happened. I still think the button shouldn't default to a broken link with an ancient version.

**Comment by s-ludwig** [comment]
(wrote this earlier but forgot to press "comment" - I'll also change the initial version to 0.8.6)

Thanks for the notice! It turned out to be caused by the process being constantly killed right after startup due to a set memory limit. This was mainly caused by the recently added JSON docs for 0.8.6, so I fixed it for now by removing 0.8.0 and 0.8.1. At some point I'll have to find out where ddox wastes so much memory for its DOM.

**Comment by schveiguy** [comment]
FYI I just saw 0.7.23 come up again. I also have noticed a lot of "bad gateway" errors when browsing the docs.
